### ISSUE TITLE
Found documentation for protocol

### ISSUE THREAD

**Issue by beached** [lnicola/co2mon#5]
Noticed int the readme that it says that it documentated.  I found the USB protocol on co2meter.com https://co2meters.com/Documentation/Other/AN_RAD_0301_USB_Communications_Revised8.pdf

**Comment by lnicola** [comment]
Thanks, I've added the link to the README. The protocol is actually a superset of that one, so I'd still argue it wasn't documented there, but an extra link doesn't hurt anyone.
